# Generated by Django 4.2.3 on 2023-09-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_smsbundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Trash', 'Trash'), ('Delete', 'Delete')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='purpose',
            field=models.CharField(choices=[('Domain Registration', 'Domain Registration'), ('Domain Renewal', 'Domain Renewal'), ('Hosting Registration', 'Hosting Registration'), ('Hosting Renewal', 'Hosting Renewal')], max_length=50),
        ),
    ]
