# Generated by Django 4.2.3 on 2023-09-28 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_packages_remove_renewal_amount_alter_renewal_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packages',
            old_name='duratioin',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='packages',
            old_name='name',
            new_name='package_name',
        ),
    ]
