# Generated by Django 4.2.3 on 2023-09-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_date_renewal_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renewal',
            old_name='start_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='renewal',
            name='package',
        ),
        migrations.AddField(
            model_name='renewal',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Packages',
        ),
    ]
