# Generated by Django 4.2.3 on 2023-10-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_renewal_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewal',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True),
        ),
    ]
