# Generated by Django 4.2.3 on 2023-10-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_renewal_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewal',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
