# Generated by Django 4.2.3 on 2023-10-14 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_renewal_renewal_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='renewal',
            old_name='renewal_date',
            new_name='days',
        ),
    ]
