# Generated by Django 4.2.3 on 2023-10-14 16:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_renewal_date_renewal_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renewal',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='renewal', to=settings.AUTH_USER_MODEL),
        ),
    ]
