# Generated by Django 4.2.3 on 2023-10-15 06:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_homepage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='description',
        ),
        migrations.AddField(
            model_name='homepage',
            name='content',
            field=tinymce.models.HTMLField(default='Hello'),
            preserve_default=False,
        ),
    ]
