# Generated by Django 4.2.3 on 2023-10-15 06:36

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_homepage_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
