# Generated by Django 4.2.3 on 2023-09-05 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_draftings'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultDrafting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('title2', models.CharField(blank=True, max_length=255, null=True)),
                ('text1', models.TextField(blank=True, null=True)),
                ('text2', models.TextField(blank=True, null=True)),
                ('text3', models.TextField(blank=True, null=True)),
                ('text4', models.TextField(blank=True, null=True)),
                ('text5', models.TextField(blank=True, null=True)),
                ('text6', models.TextField(blank=True, null=True)),
                ('text7', models.TextField(blank=True, null=True)),
                ('text8', models.TextField(blank=True, null=True)),
                ('text9', models.TextField(blank=True, null=True)),
                ('text10', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='draftings',
            name='text1',
        ),
        migrations.RemoveField(
            model_name='draftings',
            name='text10',
        ),
        migrations.RemoveField(
            model_name='draftings',
            name='text2',
        ),
        migrations.RemoveField(
            model_name='draftings',
            name='text3',
        ),
        migrations.RemoveField(
            model_name='draftings',
            name='text4',
        ),
        migrations.RemoveField(
            model_name='draftings',
            name='text5',
        ),
        migrations.RemoveField(
            model_name='draftings',
            name='text6',
        ),
        migrations.RemoveField(
            model_name='draftings',
            name='text7',
        ),
        migrations.RemoveField(
            model_name='draftings',
            name='text8',
        ),
        migrations.RemoveField(
            model_name='draftings',
            name='text9',
        ),
        migrations.RemoveField(
            model_name='draftings',
            name='title',
        ),
        migrations.RemoveField(
            model_name='draftings',
            name='title2',
        ),
        migrations.AddField(
            model_name='draftings',
            name='draft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cases.defaultdrafting'),
        ),
    ]
