# Generated by Django 4.2.3 on 2023-09-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_defaultdrafting_remove_draftings_text1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='draftings',
            name='draft',
        ),
        migrations.AddField(
            model_name='draftings',
            name='text1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftings',
            name='text10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftings',
            name='text2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftings',
            name='text3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftings',
            name='text4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftings',
            name='text5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftings',
            name='text6',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftings',
            name='text7',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftings',
            name='text8',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftings',
            name='text9',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='draftings',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='draftings',
            name='title2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
