# Generated by Django 4.2.3 on 2023-09-02 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_vatstatements_incomestatements_expensestatements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duestatements',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expensestatements',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='incomestatements',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vatstatements',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
