# Generated by Django 4.2.3 on 2023-09-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_duestatements_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duestatements',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='expensestatements',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='incomestatements',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='vatstatements',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=19, null=True),
        ),
    ]
