# Generated by Django 4.2.3 on 2023-09-05 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_draftings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Draftings',
        ),
    ]
